# Generated by Django 3.1.7 on 2021-04-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210407_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
